config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/kit-data-manager/base-repo:
      branch: main
      repo: https://github.com/kit-data-manager/base-repo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/kit-data-manager/base-repo git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-dandelion-wallaby.sh
        container: qc.acc_sickly-tangerine-mayfly
  QC.Doc:
    repos:
      github.com/kit-data-manager/base-repo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-goldenrod-zebra.sh
        container: qc.doc_baggy-linen-cuttlefish
      github.com/kit-data-manager/base-repo git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-eggplant-maltese.sh
        container: qc.doc_pasty-bronze-sparrow
      github.com/kit-data-manager/base-repo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cobalt-mongoose.sh
        container: qc.doc_chewy-saffron-quetzal
  QC.Lic:
    repos:
      github.com/kit-data-manager/base-repo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-firebrick-capuchin.sh
        container: qc.lic_wimpy-chestnut-flamingo
  QC.Met:
    repos:
      github.com/kit-data-manager/base-repo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-peach-labradoodle.sh
        container: qc.met_stinky-russet-dormouse
  QC.Sty:
    repos:
      github.com/kit-data-manager/base-repo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chartreuse-cow.sh
        container: qc.sty_foggy-ruby-tang
      github.com/kit-data-manager/base-repo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-magnolia-lion.sh
        container: qc.sty_sloppy-cerise-jaguar
      github.com/kit-data-manager/base-repo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-linen-pig.sh
        container: qc.sty_gimpy-cinnamon-wildebeest
  QC.Ver:
    repos:
      github.com/kit-data-manager/base-repo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-indigo-tiger.sh
        container: qc.ver_droopy-wisteria-goose
timeout: 5400
